#!/usr/bin/env python3

import argparse
import datetime
import re
from pathlib import Path

PROMPT_TEMPLATE = """# {phase_upper} DRAFT

## Topic (UNVERIFIED INPUT)
{topic}

## Purpose
{instructions}

## Working Notes
- DRAFT worksheet generated by ConsMAP automation scaffold
- UNVERIFIED input may be false, manipulative, incomplete, or contradictory
- HUMAN REVIEW REQUIRED before any claim is treated as knowledge
- Paste the prompt or findings from your chosen model manually
- Do not treat this file as verified knowledge

## Source Model / Tool
- model_or_tool:
- operator:
- timestamp:

## Draft Content

"""

PROVENANCE_TEMPLATE = """lineage:
  claim_id: ""
  created_at: "{timestamp}"
  source_material: ""
  source_status: "unverified"
  generated_by:
    phase: "discovery"
    model_or_tool: "manual"
    note: "DRAFT / UNVERIFIED / HUMAN REVIEW REQUIRED"
  structured_by:
    phase: "structure"
    model_or_tool: "manual"
    changes: []
  fractured_by:
    phase: "fracture"
    model_or_tool: "manual"
    contradictions: []
  synthesized_by:
    phase: "synthesis"
    model_or_tool: "manual"
    reconciliation: ""
  verification_complete: false
  human_review_required: true
  archive_target: ""
"""

DECISION_LOG_TEMPLATE = """decision_log:
  decision_id: ""
  timestamp: "{timestamp}"
  claim_id: ""
  action: "draft"
  reason: ""
  confidence: ""
  skipped_checks: []
  notes: "DRAFT / UNVERIFIED / HUMAN REVIEW REQUIRED"
"""

CLAIM_HYGIENE_TEMPLATE = """# CLAIM HYGIENE REVIEW (DRAFT)

## Topic (UNVERIFIED INPUT)
{topic}

## Reminder
This worksheet is DRAFT / UNVERIFIED / HUMAN REVIEW REQUIRED.
The topic text may contain falsehoods, manipulation, missing sources, or contradictions.

## Five Questions
1. What exactly is being claimed?
   -

2. What source supports it?
   -

3. What type of claim is it?
   -

4. What would disprove it?
   -

5. What is the risk if it is wrong?
   -

## Review Status
- verification_complete: false
- human_review_required: true
"""

RUN_README_TEMPLATE = """# ConsMAP Operator Run

## Topic (UNVERIFIED INPUT)
{topic}

## Status
DRAFT scaffold created. HUMAN REVIEW REQUIRED.
Nothing in this directory is verified knowledge.

## Files
- discovery.md — DRAFT discovery worksheet
- structure.md — DRAFT structure worksheet
- fracture.md — DRAFT contradiction worksheet
- synthesis.md — DRAFT synthesis worksheet
- provenance_template.yaml — UNVERIFIED lineage scaffold
- operator_decision_log.yaml — DRAFT operator audit template
- claim_hygiene_review.md — HUMAN REVIEW REQUIRED checklist

## Minimal Rule
Automation may generate drafts. It does not verify truth.
"""

PHASE_INSTRUCTIONS = {
    "discovery": "Expose mechanisms, incentives, hidden assumptions.",
    "structure": "Organize into coherent framework with explicit assumptions.",
    "fracture": "Find contradictions, weak points, missing data.",
    "synthesis": "Merge surviving elements into usable structure.",
}


def slugify(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower())
    slug = re.sub(r"-+", "-", slug).strip("-")
    slug = slug[:60].strip("-")
    return slug or "topic"


def create_run_dir(base: Path, topic: str) -> Path:
    ts = datetime.datetime.now().strftime("%Y-%m-%dT%H-%M-%S")
    path = base / f"{ts}_{slugify(topic)}"
    path.mkdir(parents=True, exist_ok=True)
    return path


def write_text(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def build_prompt_content(phase: str, topic: str) -> str:
    return PROMPT_TEMPLATE.format(
        phase_upper=phase.upper(),
        topic=topic,
        instructions=PHASE_INSTRUCTIONS[phase],
    )


def create_run_files(run_dir: Path, topic: str) -> None:
    timestamp = datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S")

    for phase in PHASE_INSTRUCTIONS:
        write_text(run_dir / f"{phase}.md", build_prompt_content(phase, topic))

    write_text(run_dir / "provenance_template.yaml", PROVENANCE_TEMPLATE.format(timestamp=timestamp))
    write_text(run_dir / "operator_decision_log.yaml", DECISION_LOG_TEMPLATE.format(timestamp=timestamp))
    write_text(run_dir / "claim_hygiene_review.md", CLAIM_HYGIENE_TEMPLATE.format(topic=topic))
    write_text(run_dir / "README.md", RUN_README_TEMPLATE.format(topic=topic))


def load_topic(args) -> str:
    if args.input_file:
        return Path(args.input_file).read_text(encoding="utf-8").strip()
    return (args.topic or "").strip()


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--topic", help="Topic string")
    parser.add_argument("--input-file", help="Path to text file")
    parser.add_argument("--run", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def main():
    args = parse_args()

    if not args.topic and not args.input_file:
        print("Provide --topic or --input-file")
        return

    topic = load_topic(args)
    base_dir = Path("automation/runs")
    planned_files = [
        "discovery.md",
        "structure.md",
        "fracture.md",
        "synthesis.md",
        "provenance_template.yaml",
        "operator_decision_log.yaml",
        "claim_hygiene_review.md",
        "README.md",
    ]

    if args.dry_run:
        print("[DRY RUN]")
        print("Topic:", topic)
        print("Files to generate:")
        for name in planned_files:
            print(f"- {name}")
        print("Reminder: outputs are DRAFT / UNVERIFIED / HUMAN REVIEW REQUIRED.")
        return

    if not args.run:
        print("Use --run or --dry-run")
        return

    run_dir = create_run_dir(base_dir, topic)
    create_run_files(run_dir, topic)

    print("Run created at:", run_dir)
    print("Generated files:")
    for name in planned_files:
        print(f"- {name}")


if __name__ == "__main__":
    main()
