#!/usr/bin/env python3

import argparse
import os
import datetime

TEMPLATE = """# {phase_upper} PROMPT

## Topic
{topic}

## Instructions
{instructions}

## Notes
- Generated by ConsMAP automation scaffold
- Paste into your selected model manually
"""

PHASE_INSTRUCTIONS = {
    "discovery": "Expose mechanisms, incentives, hidden assumptions.",
    "structure": "Organize into coherent framework with explicit assumptions.",
    "fracture": "Find contradictions, weak points, missing data.",
    "synthesis": "Merge surviving elements into usable structure.",
}


def slugify(text):
    return text.lower().replace(" ", "-").replace("/", "-")[:60]


def create_run_dir(base, topic):
    ts = datetime.datetime.now().strftime("%Y-%m-%dT%H-%M-%S")
    name = f"{ts}_{slugify(topic)}"
    path = os.path.join(base, name)
    os.makedirs(path, exist_ok=True)
    return path


def write_prompt(path, phase, topic):
    content = TEMPLATE.format(
        phase_upper=phase.upper(),
        topic=topic,
        instructions=PHASE_INSTRUCTIONS.get(phase, "")
    )
    filename = os.path.join(path, f"{phase}.md")
    with open(filename, "w") as f:
        f.write(content)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--topic", help="Topic string")
    parser.add_argument("--input-file", help="Path to text file")
    parser.add_argument("--run", action="store_true")
    parser.add_argument("--dry-run", action="store_true")

    args = parser.parse_args()

    if not args.topic and not args.input_file:
        print("Provide --topic or --input-file")
        return

    topic = args.topic
    if args.input_file:
        with open(args.input_file) as f:
            topic = f.read().strip()

    base_dir = "automation/runs"

    if args.dry_run:
        print("[DRY RUN]")
        print("Topic:", topic)
        print("Phases:", list(PHASE_INSTRUCTIONS.keys()))
        return

    if not args.run:
        print("Use --run or --dry-run")
        return

    run_dir = create_run_dir(base_dir, topic)

    for phase in PHASE_INSTRUCTIONS:
        write_prompt(run_dir, phase, topic)

    readme_path = os.path.join(run_dir, "README.md")
    with open(readme_path, "w") as f:
        f.write(f"Run created for topic: {topic}\n")

    print("Run created at:", run_dir)


if __name__ == "__main__":
    main()
